### ISSUE TITLE
评价函数

### ISSUE THREAD

**Issue by CQUPTNLP** [shun-zheng/Doc2EDAG#1]
针对评价函数，你是每个事件论元全部算对算一条正确记录，还是只要算对一个论元就算一条正确记录

**Comment by shun-zheng** [comment]
As for the evaluation of event table filling, briefly speaking, we calculate evaluation statistics for each event role and average them as the metric for an event type.
For more detail, please refer to the paper (6.1 Experimental Setup: Evaluation Metric) and [the code for evaluation](https://github.com/dolphin-zs/Doc2EDAG/blob/master/dee/dee_metric.py).

(I prefer to illustrate your question in English to share information with researchers all over the world.)

**Comment by CQUPTNLP** [comment]
OK,Thanks for your answer
