### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FankLi** [shun-zheng/Doc2EDAG#2]
ImportError: cannot import name 'PreTrainedBertModel'

**Comment by shun-zheng** [comment]
Please install necessary packages with the correct version [as specified](https://github.com/dolphin-zs/Doc2EDAG#Usage).

**Comment by FankLi** [comment]
It's solved! But error with 
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

conda list:
torch==1.0.1

**Comment by shun-zheng** [comment]
Please check [the issue about Pytorch](https://github.com/facebookresearch/maskrcnn-benchmark/issues/280).
