### ISSUE TITLE
about train model

### ISSUE THREAD

**Issue by SaintLogos1234** [shun-zheng/Doc2EDAG#4]
Can you provide your training model conveniently? I found that it is too time consuming to train your model. I only have one Tesla P100. I ran an epoch. It took a day. I have to run all 100 epochs. It takes 100 days, this price is too big, I can't wait, can you provide a training model?

**Comment by shun-zheng** [comment]
Due to the code refactor of some modules, the original checkpoints cannot be loaded by this open-source version.
 
I also need to train from scratch to offer a pre-trained model, and it also consumes a lot of computing resources and needs some time.
I will try to provide a pre-trained model for this repo in the next month. Sorry for the wait.

**Comment by SaintLogos1234** [comment]
Thank you for your reply. I have a question to ask，You said in the paper：we first concatenate the memory tensor m and the entity tensored,  then add them with a trainable event-role-indicator embedding，but I find in your code:
```
batch_cand_emb = batch_span_context + field_query
if self.config.use_path_mem:
         total_cand_emb = torch.cat([batch_cand_emb, prev_decode_context], dim=0).unsqueeze(0)
```
it is frist add  entity tensored with trainable event-role-indicator embedding, and then concatenate the memory tensor m, Why are the two inconsistent, is it because this method works better?

**Comment by shun-zheng** [comment]
Wow, thanks for reading the paper and codes so precisely.

As for this part you mentioned, it is not critical enough to make a distinct difference on the final performance according to our experience, and you can utilize both choices.
The most important components have been studied in the ablation tests of the paper.
